homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI 
config:

http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3 


updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction

# Text to speech
tts:
  - platform: google

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

ios:

notify:
  - platform: ios
    name: darshan_patels_iphone
    target: !secret ios_target 

sensor: !include_dir_merge_list sensor/
group: !include_dir_merge_named group/
automation: !include_dir_merge_list automation/
script: !include_dir_merge_named script/
light: !include_dir_merge_list light/
