- platform: yeelight
  devices:
    192.168.1.107:
      name: Front Light
      save_on_change: True      
    192.168.1.143:
      name: Right Light
      save_on_change: True      
    192.168.1.105:
      name: Left Light
      save_on_change: True      
