- alias: Sunset Lights
  trigger:
    platform: sun
    event: sunset
    offset: -01:00:00
  action:
    service: homeassistant.turn_on
    entity_id: group.all_lights
    data:
      brightness: '255'
      rgb_color: [255,255,255]

- alias: Midnight Lights
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turn_on
    entity_id: group.all_lights
    data: 
      brightness: '50'
      rgb_color: [244,188,66]

- alias: Sunrise Lights
  trigger:
    platform: sun
    event: sunrise
    offset: -01:00:00
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: HA Update
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.ios_darshan_patels_iphone
    data:
      message: "There is a new Home Assistant version available"  
