- alias: Harmony Activity
  trigger:
    platform: state
    entity_id: input_select.harmony_activity
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data_template: 
        activity: >
          {% if is_state("input_select.harmony_activity", "Watch TV") %}
            30104147
          {% elif is_state("input_select.harmony_activity", "Watch Fire TV") %}
            31518332
          {% elif is_state("input_select.harmony_activity", "PowerOff") %}
            -1
          {% endif %}
    - delay: 5
    - service: input_select.select_option
      data:
        entity_id: input_select.harmony_activity
        option: Select Input
